# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_run:
    workflows: ["roxygen-and-render"]
    types:
      - completed
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo 'The triggering workflow passed'
      
      - uses: actions/checkout@v3

      # needed for ssh package 
      - name: Install libssh on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install libssh-dev

      - uses: ./setup-pandoc

      - uses: ./setup-r
        with:
          use-public-rspm: true

      - uses: ./setup-r-dependencies
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
  
  pkgdown-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo 'The triggering workflow failed'